### ISSUE TITLE
Crashes on rust-lang.org domain. 

### ISSUE THREAD

**Issue by dmilith** [onur/ssl-expiration#2]
Long story short:

```rust
let expiration = SslExpiration::from_domain_name("google.com").unwrap();
assert!(!expiration.is_expired());
``` 

works fine as expected, but:

```rust
let expiration = SslExpiration::from_domain_name("rust-lang.org").unwrap();
assert!(!expiration.is_expired());
```

fails with:

```
thread 'tests::tests::test_filecheck_execute' panicked at 'called `Result::unwrap()` on an `Err` value: Error(HandshakeError("the handshake failed"), State { next_error: None, backtrace: Some(stack backtrace:
   0: error_chain::make_backtrace::hb8fb171c076e5565 (0x109e0aaef)
             at /Users/dmilith/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.10.0/src/lib.rs:417
   1: <error_chain::State as core::default::Default>::default::h9c3d1aa84c5735e1 (0x109e0ab8f)
             at /Users/dmilith/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.10.0/src/lib.rs:504
   2: ssl_expiration::error::Error::from_kind::hc7e5ec4364ed4392 (0x109e0925d)
             at /Users/dmilith/.cargo/registry/src/github.com-1ecc6299db9ec823/ssl-expiration-0.1.2/<::error_chain::error_chain::error_chain_processed macros>:52
   3: <ssl_expiration::error::Error as core::convert::From<ssl_expiration::error::ErrorKind>>::from::h0bbc7d77cf1dac70 (0x109e093b6)
             at /Users/dmilith/.cargo/registry/src/github.com-1ecc6299db9ec823/ssl-expiration-0.1.2/src/lib.rs:107
   4: ssl_expiration::SslExpiration::from_addr::hf7d8bd2b58ca6bd9 (0x109e064f8)
             at /Users/dmilith/.cargo/registry/src/github.com-1ecc6299db9ec823/ssl-expiration-0.1.2/src/lib.rs:60
   5: ssl_expiration::SslExpiration::from_domain_name::hd73dc32e795a5555 (0x109e05f47)
             at /Users/dmilith/.cargo/registry/src/github.com-1ecc6299db9ec823/ssl-expiration-0.1.2/src/lib.rs:48
   6: travmole::tests::tests::test_filecheck_execute::h3ae8e184a9619a4b (0x109c9710d)
             at src/tests.rs:219
   7: travmole::tests::tests::test_filecheck_execute::{{closure}}::h49534e5d4320faba (0x109cadc78)
             at src/tests.rs:210
   8: <F as alloc::boxed::FnBox<A>>::call_box::h0b961cc85c049bee (0x109da61a1)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:673
   9: ___rust_maybe_catch_panic (0x109e7e1ae)
             at src/libpanic_unwind/lib.rs:102
  10: std::sys_common::backtrace::__rust_begin_short_backtrace::h07f538384f587585 (0x109d9e365)
             at src/libtest/lib.rs:1426
  11: std::panicking::try::do_call::h4953be8a0738d6ec (0x109d9f154)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panicking.rs:310
  12: ___rust_maybe_catch_panic (0x109e7e1ae)
             at src/libpanic_unwind/lib.rs:102
  13: <F as alloc::boxed::FnBox<A>>::call_box::h5a5d3b35dc8857f3 (0x109da6274)
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/mod.rs:476
  14: std::sys::unix::thread::Thread::new::thread_start::hb66fd5e16b37cfd7 (0x109e7285b)
             at src/libstd/sys_common/thread.rs:24
  15: __pthread_body (0x10b6c199c)
  16: __pthread_start (0x10b6c1919)) })', src/libcore/result.rs:1009:5
```

**Comment by dmilith** [comment]
System: Darwin 10.11.6, using custom built Openssl 1.1.1a under the hood.

**Comment by dmilith** [comment]
Fixed in ssl-expiration2
